name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run: 
        working-directory: react-app
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
      # - name: Lint
      #   run: npm lint:ci
      # - name: Test
      #   run: npm test
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./react-app/build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: ./react-app/build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./react-app/build # The folder the action should deploy.